import components.computer
import components.cpu.py
import components.disk.py
import components.memory.py
import components.network.py
import components.optical_drive.py
import components.pci.py
import components.sensor
import components.sound
import components.video
