
from components.network import NetworkDevice
import sys, os

indentspace = '  '

class Printer:
  def __init__(self, output):
    self.output = output
    pass

  def print_tree(self, tree, ilevel):
    for elem in tree:
      if isinstance(elem, list):
        self.print_tree( elem, ilevel + 1)
      elif isinstance(elem, dict):
        for key, value in elem.items():
          if isinstance(value, list):
            print( "{indent}{key}:".format(indent=indentspace*ilevel, key=key), file=self.output )
            self.print_tree(value, ilevel+1)
          else:
            print( "{indent}{key}: {value}".format(indent=indentspace*ilevel, key=key, value=value), file=self.output)
            pass
          pass
        pass
      else:
        print(elem, file=self.output)
        pass
      pass
    pass
  pass
      

# Create netplan.yaml file 
def create_netplan_cfg(filename, devices):
  ethernets = []
  wifis = []
  
  SSID = os.environ.get('TRIAGE_SSID', 'wcetriage')
  WIFIPASSWORD = os.environ.get('TRIAGE_PASSWORD', 'thepasswordiswcetriage')

  for dev in devices:
    if dev.device_type == NetworkDevice.Ethernet:
      ethernets.append( { dev.device_name: [ { 'dhcp4': 'yes' }, { 'optional': 'yes' } ] } )
    elif dev.device_type == NetworkDevice.Wifi:
      # netplan works with wpa-supplicant, generates a simple config file
      # in the same directory and hands off the auth.
      wifis.append( { dev.device_name:
                      [ { 'dhcp4': 'yes' },
                        { 'optional': 'yes' },
                        { 'access-points':
                         [ { SSID : 
                             [ { 'password': WIFIPASSWORD } ]
                         } ] } ] } )
      pass
    pass

  ifdecl = [ {'version': '2' },
             {'renderer': 'networkd' } ]
  if ethernets:
    ifdecl.append( {'ethernets': ethernets } )
    pass
  if wifis:
    ifdecl.append( {'wifis': wifis} )
    pass

  netplan = [ '# This file is auto-generated by wce triage lib/netplan.py.',
              {"network": ''},
              ifdecl ]

  if filename:
    output = open(filename, "w")
  else:
    output = sys.stdout
    pass

  printer = Printer( output )
  printer.print_tree(netplan, 0)
  pass


if __name__ == "__main__":
  eth0 = NetworkDevice("eth0", device_type=NetworkDevice.Ethernet)
  eth1 = NetworkDevice("eth1", device_type=NetworkDevice.Ethernet)
  create_netplan_cfg(None, [eth0, eth1])
  pass
