from components.pci import *
from components.computer import *
from components.cpu import *
from components.memory import *
from components.disk import *
from components.network import *
from components.optical_drive import *
from components.sensor import *
from components.sound import *
from components.video import *
