#!/usr/bin/env python3

import os
import sys
import tempfile
import shutil
import subprocess

if __name__ == "__main__":
  parts = sys.argv[1:]
  for part in parts:
    dir = tempfile.mkdtemp()
    
    mount = subprocess.run("sudo -H mount {} {}".format(part, dir), shell=True)
    if mount.returncode != 0:
      sys.exit(1)
      pass
    cmd = "sudo -H rsync -av --delete /usr/local/lib/python3.6/dist-packages/ {}/usr/local/lib/python3.6/dist-packages/".format(dir)
    print(cmd)
    rsync = subprocess.run(cmd, shell=True)

    cmd = "sudo -H rsync -av /usr/local/lib/python3.6/dist-packages/wce_triage/setup/share/wce/wce-disk-images/ {}/usr/local/share/wce/wce-disk-images/".format(dir)
    print(cmd)
    rsync = subprocess.run(cmd, shell=True)

    umount = subprocess.run("sudo -H umount {}".format(part), shell=True)

    shutil.rmtree(dir)
    pass
  pass
