#!/bin/sh
#
# This is expected to run as root from chroot by network server against netclient
#
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts
#
pip3 install --upgrade --no-cache-dir -i https://test.pypi.org/simple/ --no-deps wce_triage
rm -fr /usr/local/share/wce/wce-triage-ui/*
cd /usr/local/share/wce/wce-triage-ui && wget -q -O - http://release.cleanwinner.com/wce/wce-triage-ui.tgz | tar xzf -

# clean up
umount /proc || umount -lf /proc
umount /sys
umount /dev/pts
# script end
