/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Version
         * @description Get the version number of backend
         */
        get: operations["route_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Hello
         * @description Get the version number of backend
         */
        get: operations["route_hello_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/schema/disks-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disks Event Schema */
        get: operations["_disks_event_schema_dispatch_schema_disks_event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/schema/log-message-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Message Event Schema */
        get: operations["_log_message_event_schema_dispatch_schema_log_message_event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/wipe-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Wipe Types
         * @description Returning wipe types.
         */
        get: operations["route_wipe_types_dispatch_wipe_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Triage
         * @description Handles requesting triage result
         */
        get: operations["route_triage_dispatch_triage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/music": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Music
         * @description Send ogg/mp3 stream to browser
         */
        get: operations["route_music_dispatch_music_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Messages */
        get: operations["route_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Route Messages Head */
        head: operations["route_messages_head"];
        patch?: never;
        trace?: never;
    };
    "/dispatch/cpu_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Cpu Info
         * @description Handles getting CPU rating
         */
        get: operations["route_cpu_info_dispatch_cpu_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Disk Image */
        post: operations["save_disk_image_dispatch_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/save/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Save Image */
        post: operations["route_stop_save_image_dispatch_save_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/stop-save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Save Image */
        post: operations["route_stop_save_image_dispatch_stop_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/save/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Save Status */
        get: operations["disk_save_status_dispatch_save_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/disk-save-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Save Status */
        get: operations["disk_save_status_dispatch_disk_save_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/load/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Load Status */
        get: operations["disk_load_status_dispatch_load_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/disk-load-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Load Status */
        get: operations["disk_load_status_dispatch_disk_load_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/restore-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Restore Types
         * @description Returning supported restore types.
         */
        get: operations["route_restore_types_dispatch_restore_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/disks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Disks
         * @description Handles getting the list of disks
         */
        get: operations["route_disks_dispatch_disks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/opticaldrives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Optical Drives
         * @description Handles getting the list of disks
         */
        get: operations["route_optical_drives_dispatch_opticaldrives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/disk-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Disk Images
         * @description Handles getting the list of disk images on local media
         */
        get: operations["route_disk_images_dispatch_disk_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Load Image */
        post: operations["route_load_image_dispatch_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Sync Image */
        post: operations["route_sync_image_dispatch_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Sync Status */
        get: operations["route_sync_status_alt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Sync Status */
        get: operations["route_sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Clean Image
         * @description clean disk images from the target disks
         */
        post: operations["route_clean_image_dispatch_clean_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Delete Image */
        post: operations["route_delete_image_dispatch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Rename Image */
        post: operations["route_rename_image_dispatch_rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/mount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Mount Disk
         * @description Mount disk
         */
        post: operations["route_mount_disk_dispatch_mount_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Wipe Disks */
        post: operations["route_wipe_disks_dispatch_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/wipe/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disk Wipe Status */
        get: operations["disk_wipe_status_dispatch_wipe_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/load/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Load Image */
        post: operations["route_stop_load_image_dispatch_load_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/stop-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Load Image */
        post: operations["route_stop_load_image_dispatch_stop_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/wipe/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Disk Wipe */
        post: operations["route_stop_disk_wipe_dispatch_wipe_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/stop-wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Disk Wipe */
        post: operations["route_stop_disk_wipe_dispatch_stop_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/sync/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Sync */
        post: operations["route_stop_sync_dispatch_sync_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/stop-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Stop Sync */
        post: operations["route_stop_sync_dispatch_stop_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Shutdown
         * @description shutdowns the computer.
         */
        post: operations["route_shutdown_dispatch_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/network-device-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Network Device Status
         * @description Network status
         */
        get: operations["route_network_device_status_dispatch_network_device_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/unmount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Unmount */
        post: operations["route_unmount_dispatch_unmount_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch/opticaldrive/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route Opticaldrive Test
         * @description Test optical drive
         */
        post: operations["route_opticaldrive_test_dispatch_opticaldrive_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BusType
         * @description Transport a disk is attached over, as derived from udevadm's ID_BUS/
         *     DEVPATH properties in Disk.detect_disk_type().
         * @enum {string}
         */
        BusType: "ATA" | "SCSI" | "NVME" | "USB";
        /**
         * ComponentDecision
         * @description One entry in Computer.decisions - the triage verdict for a single
         *     component, or the synthetic 'Overall' aggregate entry (which carries only
         *     component/result - no message/device/verdict).
         */
        ComponentDecision: {
            /** Component */
            component: string;
            /** Result */
            result: boolean;
            /** Message */
            message?: string | null;
            /** Device */
            device?: string | null;
            /** Verdict */
            verdict?: string[] | null;
        };
        /** CpuBenchmark */
        CpuBenchmark: {
            /** Baseline */
            baseline: number;
            /** Score */
            score?: number | null;
        };
        /** CpuInfo */
        CpuInfo: {
            /** Benchmarks */
            benchmarks: {
                [key: string]: components["schemas"]["CpuBenchmark"];
            };
            /** Rating */
            rating: string;
            /** Machine */
            machine?: string | null;
            /** Board */
            board?: string | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Config */
            config?: string | null;
            /** Memory Size */
            memory_size?: string | null;
            /** N Processors */
            n_processors?: string | null;
            /** N Physical Cores */
            n_physical_cores?: string | null;
            /** N Logical Cores */
            n_logical_cores?: string | null;
        };
        /** CpuInfoResponse */
        CpuInfoResponse: {
            cpu_info: components["schemas"]["CpuInfo"];
        };
        /**
         * DiskImageInfo
         * @description Shape of one entry from lib.disk_images.get_disk_images().
         */
        DiskImageInfo: {
            /** Mtime */
            mtime: string;
            /** Restoretype */
            restoreType: string;
            /** Name */
            name: string;
            /** Fullpath */
            fullpath: string;
            /** Size */
            size: number;
            /** Subdir */
            subdir: string;
            /** Index */
            index: number;
        };
        /**
         * DiskImageType
         * @description Shape of one entry from lib.disk_images.read_disk_image_types() - parsed
         *     directly from each image's .disk_image_type.json, plus catalogDirectory/index
         *     added by the reader. Only id/filestem/name/catalogDirectory/index are guaranteed;
         *     everything else is whatever the catalog file happened to declare.
         */
        DiskImageType: {
            /** Id */
            id: string;
            /** Filestem */
            filestem: string;
            /** Name */
            name: string;
            /** Catalogdirectory */
            catalogDirectory: string;
            /** Index */
            index: number;
            /** Timestamp */
            timestamp?: boolean | null;
            /** Media */
            media?: string | null;
            /** Efi Image */
            efi_image?: string | null;
            /** Wce Share Url */
            wce_share_url?: string | null;
            /** Partition Map */
            partition_map?: string | null;
            /** Partition Plan */
            partition_plan?: string | null;
            /** Hostname */
            hostname?: string | null;
            /** Randomize Hostname */
            randomize_hostname?: boolean | null;
            /** Cmdline */
            cmdline?: Record<string, never> | null;
        };
        /** DiskImagesResponse */
        DiskImagesResponse: {
            /** Sources */
            sources: components["schemas"]["DiskImageInfo"][];
        };
        /** DiskInfo */
        DiskInfo: {
            /**
             * Target
             * @default 0
             */
            target: number;
            /** Devicename */
            deviceName: string;
            /**
             * Runtime
             * @default 0
             */
            runTime: number;
            /**
             * Runestimate
             * @default 0
             */
            runEstimate: number;
            /** Mounted */
            mounted: boolean;
            /** Size */
            size: number;
            busType?: components["schemas"]["BusType"] | null;
            /** Model */
            model: string;
            /** Vendor */
            vendor: string;
            /** Serial No */
            serial_no: string;
            /** Smart */
            smart: boolean;
            /** Smart Enabled */
            smart_enabled: boolean;
            /** Connection Speed */
            connection_speed: number;
        };
        /**
         * DisksEvent
         * @description Payload for the 'disks' socket event (TriageServer.update_triage() ->
         *     DiskModel). Same _sequence_ convention as TriageUpdateEvent.
         */
        DisksEvent: {
            /** Disks */
            disks: components["schemas"]["DiskInfo"][];
        };
        /** DisksResponse */
        DisksResponse: {
            /** Diskpages */
            diskPages: number;
            /** Disks */
            disks: components["schemas"]["DiskInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LogMessageEvent
         * @description Payload for the 'message' socket event (UserMessages/ErrorMessages via
         *     MessageSocketIOView). severity is 1 (note) or 2 (error).
         */
        LogMessageEvent: {
            /** Message */
            message: string;
            /** Severity */
            severity: number;
        };
        /** MessageDataType */
        MessageDataType: {
            /** Start */
            start: number;
            /** Count */
            count: number;
            /** Messages */
            messages?: string[] | null;
        };
        /** NetworkDeviceStatus */
        NetworkDeviceStatus: {
            /** Device */
            device: string;
            /** Carrier */
            carrier: boolean;
        };
        /**
         * OperationProgress
         * @description Overall status of a runner (save/load/sync/wipe) plus the status of every task it holds.
         */
        OperationProgress: {
            /**
             * Report
             * @enum {string}
             */
            report: "tasks" | "task_progress" | "task_success" | "task_failure" | "run_progress";
            /** Device */
            device: string;
            runStatus: components["schemas"]["RunState"];
            /** Runmessage */
            runMessage: string;
            /**
             * Runestimate
             * @default 0
             */
            runEstimate: number;
            /**
             * Runtime
             * @default 0
             */
            runTime: number;
            /** Step */
            step?: number | null;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskStatus"][];
        };
        /** OpticalDriveInfo */
        OpticalDriveInfo: {
            /** Devicename */
            deviceName: string;
            /** Model */
            model: string;
        };
        /** OpticalDrivesResponse */
        OpticalDrivesResponse: {
            /** Opticaldrives */
            opticaldrives: components["schemas"]["OpticalDriveInfo"][];
        };
        /** RestoreTypesResponse */
        RestoreTypesResponse: {
            /** Restoretypes */
            restoreTypes: components["schemas"]["DiskImageType"][];
        };
        /**
         * RunState
         * @description Run state of a runner/task. Values double as the wire representation
         *     used in NDJSON progress reports (the `runStatus` field).
         * @enum {string}
         */
        RunState: "Waiting" | "Prepare" | "Preflight" | "Running" | "Success" | "Failed";
        /**
         * TaskStatus
         * @description Describes one op_task (or, for a task representing several parallel
         *     subprocess targets, one of its describe_subtasks() entries).
         */
        TaskStatus: {
            /** Step */
            step: number;
            /** Taskcategory */
            taskCategory: string;
            /** Taskprogress */
            taskProgress: number;
            /** Taskestimate */
            taskEstimate: number;
            /** Taskelapse */
            taskElapse: number;
            /**
             * Taskstatus
             * @enum {string}
             */
            taskStatus: "waiting" | "running" | "done" | "fail";
            /** Taskmessage */
            taskMessage?: string | null;
            /** Taskexplain */
            taskExplain: string;
            /**
             * Taskverdict
             * @default []
             */
            taskVerdict: string[];
        };
        /**
         * TriageUpdateEvent
         * @description Payload for the 'triageupdate' socket event, and the GET /triage response
         *     (same underlying server._triage model). TriageServer.send_to_ui() adds a
         *     top-level `_sequence_` key once this is dispatched - the same mechanism the
         *     disks/loadimage/saveimage/zerowipe/diskimage events rely on - so the model
         *     intentionally doesn't declare that field itself.
         */
        TriageUpdateEvent: {
            /** Components */
            components: components["schemas"]["ComponentDecision"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WipeType */
        WipeType: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arg */
            arg?: string | null;
        };
        /** WipeTypesResponse */
        WipeTypesResponse: {
            /** Wipetypes */
            wipeTypes: components["schemas"]["WipeType"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    route_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    route_hello_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    _disks_event_schema_dispatch_schema_disks_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisksEvent"];
                };
            };
        };
    };
    _log_message_event_schema_dispatch_schema_log_message_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogMessageEvent"];
                };
            };
        };
    };
    route_wipe_types_dispatch_wipe_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WipeTypesResponse"];
                };
            };
        };
    };
    route_triage_dispatch_triage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageUpdateEvent"];
                };
            };
        };
    };
    route_music_dispatch_music_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    route_messages: {
        parameters: {
            query?: {
                start?: number;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDataType"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_messages_head: {
        parameters: {
            query?: {
                start?: number;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDataType"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_cpu_info_dispatch_cpu_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CpuInfoResponse"];
                };
            };
        };
    };
    save_disk_image_dispatch_save_post: {
        parameters: {
            query: {
                deviceName: string;
                type: string;
                destination?: string;
                partition?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_stop_save_image_dispatch_save_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_save_image_dispatch_stop_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    disk_save_status_dispatch_save_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    disk_save_status_dispatch_disk_save_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    disk_load_status_dispatch_load_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    disk_load_status_dispatch_disk_load_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_restore_types_dispatch_restore_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreTypesResponse"];
                };
            };
        };
    };
    route_disks_dispatch_disks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisksResponse"];
                };
            };
        };
    };
    route_optical_drives_dispatch_opticaldrives_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpticalDrivesResponse"];
                };
            };
        };
    };
    route_disk_images_dispatch_disk_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskImagesResponse"];
                };
            };
        };
    };
    route_load_image_dispatch_load_post: {
        parameters: {
            query: {
                deviceNames: string;
                newhostname?: string;
                source: string;
                /** @description Image file size, if known */
                size?: string | null;
                /** @description Disk restore type */
                restoretype: string;
                /** @description Wipe request */
                wipe_request?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_sync_image_dispatch_sync_post: {
        parameters: {
            query: {
                sources: string;
                deviceNames: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_sync_status_alt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_clean_image_dispatch_clean_post: {
        parameters: {
            query: {
                deviceNames: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_delete_image_dispatch_delete_post: {
        parameters: {
            query: {
                name: string;
                restoretype: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_rename_image_dispatch_rename_post: {
        parameters: {
            query: {
                from: string;
                to: string;
                restoretype: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_mount_disk_dispatch_mount_post: {
        parameters: {
            query: {
                deviceName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_wipe_disks_dispatch_wipe_post: {
        parameters: {
            query: {
                deviceNames: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disk_wipe_status_dispatch_wipe_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_load_image_dispatch_load_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_load_image_dispatch_stop_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_disk_wipe_dispatch_wipe_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_disk_wipe_dispatch_stop_wipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_sync_dispatch_sync_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_stop_sync_dispatch_stop_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
    route_shutdown_dispatch_shutdown_post: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_network_device_status_dispatch_network_device_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkDeviceStatus"][];
                };
            };
        };
    };
    route_unmount_dispatch_unmount_post: {
        parameters: {
            query: {
                deviceNames: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_opticaldrive_test_dispatch_opticaldrive_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationProgress"];
                };
            };
        };
    };
}
